let state,dirty=false,pending=0,removedDay=null;
const cardObjects=new WeakMap(),cardOpen=new WeakMap();
function rememberCards(){document.querySelectorAll('#schedule>details,#prizes>details,#rides>details').forEach(d=>{const item=cardObjects.get(d);if(item)cardOpen.set(item,d.open)});}
function card(item,initial=false){const d=el('details');d.open=cardOpen.has(item)?cardOpen.get(item):initial;cardObjects.set(d,item);return d;}
function movers(list,item,label){return [-1,1].map(delta=>{const index=list.indexOf(item);const b=button(`Move ${label} ${delta<0?'up':'down'}`,()=>{const i=list.indexOf(item),next=i+delta;if(next<0||next>=list.length)return;[list[i],list[next]]=[list[next],list[i]];changed();render()});b.disabled=index+delta<0||index+delta>=list.length;return b;});}
const status=document.querySelector('#status');
function changed(){dirty=true;status.textContent='Unsaved changes';}
function el(tag,text){const e=document.createElement(tag);if(text)e.textContent=text;return e;}
function button(text,fn){const b=el('button',text);b.type='button';b.onclick=fn;return b;}
function field(parent,label,obj,key,multiline=false){const l=el('label',label);const i=el(multiline?'textarea':'input');i.value=obj[key]||'';i.oninput=()=>{obj[key]=i.value;changed()};l.append(i);parent.append(l);return i;}
async function request(url,data){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','X-Grit-Editor':'1'},body:JSON.stringify(data)});const v=await r.json();if(!r.ok)throw Error(v.error||'Save failed');return v;}
function upload(parent,label,onUpload,multiple=false){const l=el('label',label),input=el('input');input.type='file';input.accept='image/png,image/jpeg,image/webp,image/gif,image/avif';input.multiple=multiple;input.onchange=async()=>{pending++;document.querySelector('#save').disabled=true;try{for(const f of input.files){if(f.size>2500000)throw Error('Image must be under 2.5 MB.');const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=reject;reader.readAsDataURL(f)});const result=await request('/api/upload',{data,revision:state.revision});state.revision=result.revision;onUpload(result.path)}changed();const scrollPosition=window.scrollY;render();window.scrollTo(0,scrollPosition)}catch(e){status.textContent=e.message}finally{pending--;document.querySelector('#save').disabled=pending>0}};l.append(input);parent.append(l);}
function render(){rememberCards();const schedule=document.querySelector('#schedule');schedule.replaceChildren();state.schedule.forEach((day,di)=>{const d=card(day,true);d.append(el('summary',day.name),...movers(state.schedule,day,'day'));const grid=el('div');grid.className='grid';field(grid,'Day name',day,'name');field(grid,'Date',day,'date');d.append(grid);day.events.forEach((event,ei)=>{const f=el('fieldset');f.append(el('legend',`Event ${ei+1}`));field(f,'Time',event,'time');field(f,'Title',event,'title');field(f,'Description',event,'description',true);const l=el('label','Link to guide page');const select=el('select');['','schedule','food','raffle','workshops','group-rides','maps','on-bike-clinics','scavenger-hunt'].forEach(v=>{const o=el('option',v||'No link');o.value=v;select.append(o)});select.value=event.link||'';select.onchange=()=>{event.link=select.value;changed()};l.append(select);f.append(l,...movers(day.events,event,'event'),button('Remove event',()=>{day.events.splice(ei,1);changed();render()}));d.append(f)});d.append(button('Add event',()=>{day.events.push({time:'TBA',title:'New event',description:'',link:''});changed();render()}),button('Remove day',()=>{removedDay={day,index:di};state.schedule.splice(di,1);changed();render()}));schedule.append(d)});
if(removedDay)schedule.append(button('Undo remove day',()=>{state.schedule.splice(removedDay.index,0,removedDay.day);removedDay=null;changed();render()}));
const rides=document.querySelector('#rides');rides.replaceChildren();(state.rides||[]).forEach((ride,i)=>{const d=card(ride);d.append(el('summary',ride.title||'New ride'),...movers(state.rides,ride,'ride'));for(const [label,key] of [['Title','title'],['Day / date','date'],['Time','time'],['Distance','distance'],['Ride badge','badge'],['Route link','routeUrl']])field(d,label,ride,key);field(d,'Description',ride,'description',true);d.append(button('Remove ride',()=>{state.rides.splice(i,1);changed();render()}));rides.append(d)});
const prizes=document.querySelector('#prizes');prizes.replaceChildren();state.raffle.prizes.forEach((prize,pi)=>{const d=card(prize);d.append(el('summary',prize.name||'New prize'),...movers(state.raffle.prizes,prize,'prize'));field(d,'Prize name',prize,'name');field(d,'Sponsor name',prize,'donor');if(prize.logo){const img=el('img');img.src='https://get2grit.bike/'+prize.logo;img.alt='Sponsor logo preview';img.className='preview';d.append(img,button('Remove logo',()=>{prize.logo='';changed();render()}))}upload(d,'Upload sponsor logo',path=>prize.logo=path);prize.images.forEach((path,i)=>{const box=el('div'),img=el('img');img.src='https://get2grit.bike/'+path;img.alt='Prize image preview';img.className='preview';box.append(img,button('Remove image',()=>{prize.images.splice(i,1);changed();render()}));d.append(box)});upload(d,'Upload prize images',path=>prize.images.push(path),true);d.append(button('Remove prize',()=>{state.raffle.prizes.splice(pi,1);changed();render()}));prizes.append(d)});}
document.querySelector('#save').onclick=async()=>{if(!state||pending)return;try{const result=await request('/api/content',state);state.revision=result.revision;dirty=false;status.textContent='Saved to GitHub. The live site updates after deployment completes.'}catch(e){status.textContent=e.message}};
document.querySelector('#add-ride').onclick=()=>{state.rides??=[];state.rides.push({title:'New ride',date:'',time:'',distance:'',badge:'NO-DROP',routeUrl:'',description:''});changed();render()};
document.querySelector('#add-day').onclick=()=>{state.schedule.push({name:'New day',date:'',events:[]});changed();render()};document.querySelector('#add-prize').onclick=()=>{state.raffle.prizes.push({name:'New prize',donor:'',logo:'',images:[]});changed();render()};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
fetch('/api/content').then(r=>{if(!r.ok)throw Error('Sign in with GitHub to load the editor.');return r.json()}).then(v=>{state=v;render();renderCoaches();status.textContent='Ready';loadCopyPage()}).catch(e=>status.textContent=e.message);

document.querySelector('#logout').onclick=async()=>{await request('/api/logout',{});location.reload()};
